---

# =============================================================================
# PLAY - Reset password (runs on windows group)
# -----------------------------------------------------------------------------

- name: Reset user password in Active Directory
  hosts: windows
  gather_facts: no
  vars:
    userid: "{{ lookup('env', 'USER_USERID') }}"
  tasks:

  - name: Create random password
    set_fact: random_password={{ lookup('password', '/dev/null') }}

  # - debug: var=random_password verbosity=1

  - name: Assign random password to user
    win_domain_user:
      name: "{{ userid }}"
      password: "{{ random_password }}"
      password_never_expires: yes
    register: new_user

  # - debug: var=new_user verbosity=1

# =============================================================================
# PLAY - Notify user (runs on localhost)
# -----------------------------------------------------------------------------

- name: Notify user
  hosts: localhost
  gather_facts: no
  vars:
    random_password: "{{hostvars[groups['windows'][0]]['random_password']}}"
    userid: "{{ lookup('env', 'USER_USERID') }}"
  tasks:

  - name: Display all variables for debug
    debug: var=vars verbosity=1

  - name: Send message to new user
    mail:
      body: "{{ lookup('template', 'templates/notify-reset.htm') }}"
      cc: wwdc-labadmins@cisco.com
      charset: utf-8
      from: wwdc-labadmins@cisco.com
      # host: outbound.cisco.com
      host: smtp-ext.cisco.com
      port: 25
      secure: never
      subject: Your AUSLAB password has been reset
      subtype: html
      timeout: 20
      # to: Doron Chosnek <dchosnek@cisco.com>
      to: "{{ userid }}@cisco.com"
